server:
    port: ${SERVER_PORT}

# General JPA properties
#spring.jpa.database=POSTGRESQL
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# DataSource configuration

spring: 
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGSQL_HOST}:${PGSQL_PORT}/${PGSQL_DBNAME}
    username: ${PGSQL_USER}
    password: ${PGSQL_PASS}

